return {
	require("shiv.plugins.colorscheme"),
	require("shiv.plugins.bufferline"),
	require("shiv.plugins.formatting"),
	require("shiv.plugins.nvim-tree"),
	require("shiv.plugins.telescope"),
	require("shiv.plugins.lualine"),
	require("shiv.plugins.treesitter"),
	require("shiv.plugins.gitsigns"),
	require("shiv.plugins.indent-blankline"),
	require("shiv.plugins.undotree"),
	require("shiv.plugins.autopairs"),
	require("shiv.plugins.git-stuff"),
	require("shiv.plugins.lsp"),
	require("shiv.plugins.remote-nvim"),
}
